### ISSUE TITLE
ReferenceError: Can't find variable: inputSearch

### ISSUE THREAD

**Issue by soggybag** [KingGenius5/Giphy-Finder#5]
https://github.com/KingGenius5/Giphy-Finder/blob/a4ace4e8b7612891235753ac400f42e06112184a/main.js#L13

Looks like you have `inputSearch` here but never defined it!

Take a clue from:

`const searchForm = document.getElementById('search-form')`

add one of these for the input element. 

`const inputSearch = document.getElementById('input-search')`

Bingo!

**Comment by KingGenius5** [comment]
Hey Mitchell, I was confused as to why I was getting so many errors and as I was going through your issues I realized I had already done these steps. The problem was it was working locally and I forgot to push my changes to GitHub. The repo is now up to date and works (see README link to get to GitHub pages deployment).
